# your_project/
# ├─ .streamlit/
# │  └─ config.toml
# └─ app.py

[theme]
base="light"
primaryColor="slateBlue"
backgroundColor="white"
secondaryBackgroundColor="darkSeaGreen"
baseRadius="full"
font = "Candara"
headingfont = "Bradley Hand ITC "

[theme.sidebar]
backgroundColor="Cornsilk"
secondaryBackgroundColor="Cornsilk"
baseRadius="none"
font = "Candara"
headingfont = "Bradley Hand ITC"

